// This file is auto-generated by scripts/generate_robot_constants.js

export const AVAILABLE_ROBOTS = [
  "bi_so100_follower",
  "hope_jr",
  "koch_follower",
  "lekiwi",
  "so100_follower",
  "so101_follower",
  "stretch3",
  "viperx"
] as const;

export const AVAILABLE_TELEOPERATORS = [
  "bi_so100_leader",
  "gamepad",
  "homunculus",
  "keyboard",
  "koch_leader",
  "so100_leader",
  "so101_leader",
  "stretch3_gamepad",
  "widowx"
] as const;
