CREATE TYPE "public"."cameraModality" AS ENUM('real', 'simulated');--> statement-breakpoint
CREATE TYPE "public"."robotModality" AS ENUM('real', 'simulated');--> statement-breakpoint
CREATE TABLE "cameras" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cameras_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"serial_number" varchar DEFAULT '',
	"name" varchar DEFAULT '',
	"resolution" varchar DEFAULT '',
	"fps" integer DEFAULT 0,
	"pos_x" real DEFAULT 0,
	"pos_y" real DEFAULT 0,
	"pos_z" real DEFAULT 0,
	"quat_w" real DEFAULT 1,
	"quat_x" real DEFAULT 0,
	"quat_y" real DEFAULT 0,
	"quat_z" real DEFAULT 0,
	"xyaxes_x1" real DEFAULT 1,
	"xyaxes_y1" real DEFAULT 0,
	"xyaxes_z1" real DEFAULT 0,
	"xyaxes_x2" real DEFAULT 0,
	"xyaxes_y2" real DEFAULT 1,
	"xyaxes_z2" real DEFAULT 0,
	"data" json DEFAULT '{}'::json,
	"modality" "cameraModality" DEFAULT 'real',
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "episodes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "episodes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar NOT NULL,
	"session_id" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "robot_models" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "robot_models_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar NOT NULL,
	"dir_name" varchar NOT NULL,
	"class_name" varchar NOT NULL,
	"config_class_name" varchar NOT NULL,
	"properties" json DEFAULT '{}'::json,
	"model_xml" text,
	"model_path" varchar,
	"model_format" varchar,
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "robots" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "robots_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"serial_number" varchar DEFAULT '',
	"name" varchar DEFAULT '',
	"notes" text DEFAULT '',
	"data" json DEFAULT '{}'::json,
	"robot_model_id" integer,
	"modality" "robotModality" DEFAULT 'real',
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "scene_cameras" (
	"scene_id" integer NOT NULL,
	"camera_id" integer NOT NULL,
	"snapshot" jsonb NOT NULL,
	CONSTRAINT "scene_cameras_scene_id_camera_id_pk" PRIMARY KEY("scene_id","camera_id")
);
--> statement-breakpoint
CREATE TABLE "scene_robots" (
	"scene_id" integer NOT NULL,
	"robot_id" integer NOT NULL,
	"snapshot" jsonb NOT NULL,
	CONSTRAINT "scene_robots_scene_id_robot_id_pk" PRIMARY KEY("scene_id","robot_id")
);
--> statement-breakpoint
CREATE TABLE "scene_teleoperators" (
	"scene_id" integer NOT NULL,
	"teleoperator_id" integer NOT NULL,
	"snapshot" jsonb NOT NULL,
	CONSTRAINT "scene_teleoperators_scene_id_teleoperator_id_pk" PRIMARY KEY("scene_id","teleoperator_id")
);
--> statement-breakpoint
CREATE TABLE "scenes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "scenes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar NOT NULL,
	"scene_xml_path" varchar,
	"notes" text,
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "sessions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sessions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar NOT NULL,
	"skill_id" integer,
	"scene_id" integer NOT NULL,
	"dataset_dir" text DEFAULT '',
	"dataset_config" jsonb DEFAULT '{}'::jsonb,
	"scene_snapshot" jsonb DEFAULT '{}'::jsonb,
	"initial_scene_state" jsonb,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "skills" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "skills_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar NOT NULL,
	"description" text,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "teleoperator_models" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "teleoperator_models_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"class_name" varchar NOT NULL,
	"config_class_name" varchar NOT NULL,
	"data" json DEFAULT '{}'::json,
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "teleoperators" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "teleoperators_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"serial_number" varchar DEFAULT '',
	"name" varchar DEFAULT '',
	"model" varchar DEFAULT '',
	"notes" text DEFAULT '',
	"data" json DEFAULT '{}'::json,
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "user_config" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_config_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" uuid,
	"config" json DEFAULT '{}'::json
);
--> statement-breakpoint
ALTER TABLE "episodes" ADD CONSTRAINT "episodes_session_id_sessions_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."sessions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "robots" ADD CONSTRAINT "robots_robot_model_id_robot_models_id_fk" FOREIGN KEY ("robot_model_id") REFERENCES "public"."robot_models"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "scene_cameras" ADD CONSTRAINT "scene_cameras_scene_id_scenes_id_fk" FOREIGN KEY ("scene_id") REFERENCES "public"."scenes"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "scene_cameras" ADD CONSTRAINT "scene_cameras_camera_id_cameras_id_fk" FOREIGN KEY ("camera_id") REFERENCES "public"."cameras"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "scene_robots" ADD CONSTRAINT "scene_robots_scene_id_scenes_id_fk" FOREIGN KEY ("scene_id") REFERENCES "public"."scenes"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "scene_robots" ADD CONSTRAINT "scene_robots_robot_id_robots_id_fk" FOREIGN KEY ("robot_id") REFERENCES "public"."robots"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "scene_teleoperators" ADD CONSTRAINT "scene_teleoperators_scene_id_scenes_id_fk" FOREIGN KEY ("scene_id") REFERENCES "public"."scenes"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "scene_teleoperators" ADD CONSTRAINT "scene_teleoperators_teleoperator_id_teleoperator_models_id_fk" FOREIGN KEY ("teleoperator_id") REFERENCES "public"."teleoperator_models"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_skill_id_skills_id_fk" FOREIGN KEY ("skill_id") REFERENCES "public"."skills"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_scene_id_scenes_id_fk" FOREIGN KEY ("scene_id") REFERENCES "public"."scenes"("id") ON DELETE cascade ON UPDATE no action;