CREATE TABLE "usb_vendors" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "usb_vendors_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"company" varchar NOT NULL,
	"vendor_id" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE "robots" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP TABLE "robots" CASCADE;--> statement-breakpoint
ALTER TABLE "scene_robots" DROP CONSTRAINT "scene_robots_robot_id_robots_id_fk";
--> statement-breakpoint
ALTER TABLE "scene_robots" ADD CONSTRAINT "scene_robots_robot_id_robot_models_id_fk" FOREIGN KEY ("robot_id") REFERENCES "public"."robot_models"("id") ON DELETE cascade ON UPDATE no action;