const fs = require('fs');
const path = require('path');

const projectRoot = path.resolve(__dirname, '..');
const pythonEnvPath = path.join(projectRoot, 'src/python/.venv/lib/python3.10/site-packages/lerobot');
const robotsPath = path.join(pythonEnvPath, 'robots');
const teleoperatorsPath = path.join(pythonEnvPath, 'teleoperators');
const outputPath = path.join(projectRoot, 'src/lib/constants.ts');

function getDirectories(source) {
  if (!fs.existsSync(source)) {
    console.warn(`Directory not found: ${source}`);
    return [];
  }
  return fs.readdirSync(source, { withFileTypes: true })
    .filter(dirent => dirent.isDirectory() && dirent.name !== '__pycache__')
    .map(dirent => dirent.name);
}

const robots = getDirectories(robotsPath);
const teleoperators = getDirectories(teleoperatorsPath);

const fileContent = `// This file is auto-generated by scripts/generate_robot_constants.js

export const AVAILABLE_ROBOTS = ${JSON.stringify(robots, null, 2)} as const;

export const AVAILABLE_TELEOPERATORS = ${JSON.stringify(teleoperators, null, 2)} as const;
`;

fs.writeFileSync(outputPath, fileContent);
console.log(`Generated ${outputPath}`);
console.log('Robots:', robots);
console.log('Teleoperators:', teleoperators);
